version: '3.8'

services:
  downstream-service:
    build:
      context: ./downstream-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-network

  spring-resilience-demo:
    build:
      context: ./spring-resilience-demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - API_BASE_URL=http://downstream-service:8081
    depends_on:
      downstream-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge 